@startuml
'https://plantuml.com/class-diagram

abstract class AbstractFlyingObject
{
    # locationX:int
    # locationY:int
    # speedX:int
    # speedY:int
    # image:BufferedImage
    # width:int
    # height:int
    # isValid:boolean

    + AbstractFlyingObject(int locationX, int locationY, int speedX, int speedY)
    + forward():void
    + crash(AbstractFlyingObject flyingObject):boolean
    + setLocation(double locationX, double locationY):void
    + getLocationX():int
    + getLocationY():int
    + getSpeedY():int
    + getImage():BufferedImage
    + getWidth():int
    + getHeight():int
    + notValid():boolean
    + vanish():void
}

abstract class AbstractAircraft
{
	# maxHp:int
    # hp:int
    + AbstractAircraft(int locationX, int locationY, int speedX, int speedY, int hp)
    + decreaseHp(int decrease):void
    + getHp():int
    + {abstract} shoot():List<BaseBullet>
 }

' --- 敌机工厂模式 (Factory Method Pattern) ---

interface EnemyFactory {
    + createEnemy(): AbstractAircraft
}

class MobEnemyFactory {
    + createEnemy(): AbstractAircraft
}

class EliteEnemyFactory {
    + createEnemy(): AbstractAircraft
}

class ExcellentEnemyFactory {
    + createEnemy(): AbstractAircraft
}

class AceEnemyFactory {
    + createEnemy(): AbstractAircraft
}

class BossEnemyFactory {
    + createEnemy(): AbstractAircraft
}

EnemyFactory <|.. MobEnemyFactory
EnemyFactory <|.. EliteEnemyFactory
EnemyFactory <|.. ExcellentEnemyFactory
EnemyFactory <|.. AceEnemyFactory
EnemyFactory <|.. BossEnemyFactory

EnemyFactory ..> AbstractAircraft : <<create>>

' --- 飞机相关类 ---

class HeroAircraft <<Singleton>> {
    - {static} instance: HeroAircraft
    - HeroAircraft(int locationX, int locationY, int speedX, int speedY, int hp)
    + {static} getInstance(int locationX, int locationY, int speedX, int speedY, int hp): HeroAircraft
    + forward():void
    + shoot():List<BaseBullet>
}

AbstractAircraft <|-- HeroAircraft

class MobEnemy {
    + MobEnemy(int locationX, int locationY, int speedX, int speedY, int hp)
}

class ExcellentEnemy {
    + ExcellentEnemy(int locationX, int locationY, int speedX, int speedY, int hp)
}

class EliteEnemy {
    + EliteEnemy(int locationX, int locationY, int speedX, int speedY, int hp)
}

class BossEnemy {
    + BossEnemy(int locationX, int locationY, int speedX, int speedY, int hp)
}

class AceEnemy {
    + AceEnemy(int locationX, int locationY, int speedX, int speedY, int hp)
}

AbstractAircraft <|-- MobEnemy
MobEnemy <|-- ExcellentEnemy
MobEnemy <|-- EliteEnemy
MobEnemy <|-- BossEnemy
MobEnemy <|-- AceEnemy

' --- 子弹相关类 ---

abstract class BaseBullet
{
    - power:int
    + BaseBullet(int locationX, int locationY, int speedX, int speedY, int power)
    + forward():void
	+ getPower():int
}

class HeroBullet
class EnemyBullet

BaseBullet <|-- HeroBullet
BaseBullet <|-- EnemyBullet

' --- 道具相关类与简单工厂 (Simple Factory Pattern) ---

interface Item {
    + {abstract} active(HeroAircraft hero):void
}

abstract class AbstractProp {
    + AbstractProp(int locationX, int locationY, int speedX, int speedY)
}

' AbstractProp 继承自飞行对象，并实现 Item 接口
AbstractFlyingObject <|-- AbstractProp
Item <|.. AbstractProp

class BombProp {
    + active(HeroAircraft hero):void
}

class FireProp {
    + active(HeroAircraft hero):void
}

class HpProp {
    + active(HeroAircraft hero):void
}

class SuperFireProp {
    + active(HeroAircraft hero):void
}

AbstractProp <|-- BombProp
AbstractProp <|-- FireProp
AbstractProp <|-- HpProp
AbstractProp <|-- SuperFireProp

class propFactory {
    + createProp(String type, int x, int y, int speedX, int speedY): Item
}

' 工厂生产的是符合 Item 接口的对象
propFactory ..> Item : <<create>>

' --- 整体结构 ---
AbstractFlyingObject <|-- AbstractAircraft
AbstractFlyingObject <|-- BaseBullet

@enduml